### ISSUE TITLE
How to pass in multiple values for a single argument

### ISSUE THREAD

**Issue by albeethekid** [mghoneimy/php-graphql-client#1]
Hi there, could someone please tell me how to use this library to make the follow query?

```
{
  nodes(ids: ["gid://shopify/Product/123", "gid://shopify/Product/456"]) {
    ...on Product {
      title
    }
  }
}
```

**Comment by mghoneimy** [comment]
Hello,
I have been working on a couple of new features over the past week, one of them is to enable array and object filters. I'm merging these features tonight, will update you on how to do this as soon as that's done.

**Comment by mghoneimy** [comment]
@albeethekid That's how you can pass multiple values for a single argument:
$query = (new Query('nodes'))
    ->setArguments(['gid' => ['gid://shopify/Product/123', 'gid://shopify/Product/456']])
    );

Please refer to the update README for more:
https://github.com/mghoneimy/php-graphql-client#query-example-query-with-array-argument

**Comment by albeethekid** [comment]
Really appreciate you adding that feature so quickly. And thank you for creating this library!
