### ISSUE TITLE
Incorrect return type hint in GraphQL\Client::runQuery and GraphQL\Client::runRawQuery

### ISSUE THREAD

**Issue by rembertin** [mghoneimy/php-graphql-client#11]
Hello,

I've found a little issue in your code : the methods `GraphQL\Client::runQuery` and `GraphQL\Client::runRawQuery` are type-hinted `?Results`, so they are supposed to return a `GraphQL\Results` or `null`, but in fact these methods can't return `null` (or I'm missing a point).
Is it possible to change the return type-hint to simply `Results` ?

Thanks and congrats for your awesome job!

**Comment by mghoneimy** [comment]
@rembertin You're actually right, I probably changed the implementation but forgot the type hint. I'll make sure to include this in the next release.

Thanks man, please :star: the repo if you found it useful :smile:

**Comment by mghoneimy** [comment]
Issue fixed in release 1.3.1
