### ISSUE TITLE
Arguments contructor do not handle nulled arguments

### ISSUE THREAD

**Issue by Zaboday** [mghoneimy/php-graphql-client#13]
Hello!

When I am trying create Mutation with argument value `null`, Query::constructArguments() makes empty value string in query.

For example arguments: `['foo' => 1, 'bar' => null, 'some' => '1']`
Result: `(foo: 1 bar:  some: "1")` instead of `(foo: 1 bar: null  some: "1")`

It is becouse `null` is not sclar, and `constructArguments()` makes simple type conversion `null` to `string`.

Thank Guys! Very helpful library!

**Comment by mghoneimy** [comment]
@Zaboday Oops, I will make sure I fix this by EOD tomorrow. It should be an easy fix! Please :star: the repo if you found useful in your work.
Thank you! :smile:

**Comment by mghoneimy** [comment]
Fix deployed in release 1.3.1
