### ISSUE TITLE
Consuming Api with pagination

### ISSUE THREAD

**Issue by avfigueredo** [mghoneimy/php-graphql-client#18]
Hi, there's a way or example of how i can consume a api graphql where there is pagination? 

I'm trying consuming this news api:

```
{
  news {
    data {
      id
      subject
      body
      imageUrl
      createdAt
      category {
        id
        description
        icon
        color
      }
    }
    total
    per_page
  }
}
```

I tried this examples, but doesn't works. Can you me give a help?

```
$query = (new Query('news'))
                    ->setSelectionSet([
                        'id',
                        'subject',
                        'body',
                        'createdAt',
                        'imageUrl',
                    ]);
```

```
$query = (new Query('news'))
                    ->setSelectionSet([
                       'data' => [
                        'id',
                        'subject',
                        'body',
                        'createdAt',
                        'imageUrl',
]
                    ]);
```

Tks!

**Comment by mghoneimy** [comment]
hi @avfigueredo 
Typically, GraphQL API's provide arguments for the fields which allows you to control the page being loaded for that field. Usually the names of these arguments are "first" and "offset" which allow you to control the offset you want to start loading from the how many items you want to load starting from there.

Please refer tot he GraphQL manual for more info about arguments:
https://graphql.org/learn/queries/#arguments
