### ISSUE TITLE
Do you support Enum Types?

### ISSUE THREAD

**Issue by jbalbert** [mghoneimy/php-graphql-client#20]
Hello,

I am currently using this package and currently trying to connect to a graphQL client.

I have this setArguments which the types is in ENUM. below: 

 ->setArguments([ 'types' => 'GENERAL', 'languages' => ["en"]])

I tried to sent the request to the graphQl client but I always get this message.

"message": "Expected type DescriptionType!, found \\\"GENERAL\\\". Did you mean the enum value GENERAL?

I just want to ask how do you send Enum Values in a grapql client using setArguments or do i need to use the setVariables?
Can you please show an example?

Thank you!

**Comment by mghoneimy** [comment]
Hello @jbalbert , I will look into this tomorrow and provide you with an example.

**Comment by jbalbert** [comment]
Hi @mghoneimy , Thank you very much for your response that would be a really big help.

**Comment by mghoneimy** [comment]
@jbalbert Generally, to write raw text in the query (an example would be a non-string ENUM type, or an input object) you would use the RawObject class provided in this library. Here's your example:
```->setArguments([ 'types' => new RawObject('GENERAL'), 'languages' => ["en"]])```

Hope this helps :)

**Comment by jbalbert** [comment]
Hello @mghoneimy ,

I just tested it and it now works.

Thanks for your help! :)
