### ISSUE TITLE
No Mutation and Query Builder Class for lower versions

### ISSUE THREAD

**Issue by jbalbert** [mghoneimy/php-graphql-client#21]
Hello @mghoneimy ,
 
I just want to know why there are no Mutation Class and Query Builder in the lower version
of this package?

Currently, when we require this package via composer the below version is the one that we 
are using since we are using php version 7.0..

"gmostafa/php-graphql-client": "^0.3.5"

When we tried using query builder and mutation it always say Mutation and Query Builder class not found.

Checking the package the class for mutation and query builder is missing.

![graphQLpackage](https://user-images.githubusercontent.com/8281900/67823109-c5dfec80-fafc-11e9-9b80-96d83c91cee4.png)

**Comment by jbalbert** [comment]
Hello @mghoneimy,

May I ask any update about this?

Thank you!

**Comment by mghoneimy** [comment]
@jbalbert The `Mutation` and `QueryBuilder` classes were only added in higher versions of this package as you might have noticed, PHP7.1+. There's no way you can get access to these features without upgrading your PHP version to at least 7.1. PHP7.0 went out of support at the beginning of this year and no new features will be added using it.
