### ISSUE TITLE
Client constructor and documentation mismatch

### ISSUE THREAD

**Issue by mschop** [mghoneimy/php-graphql-client#22]
Hi all,

in the REAME.md in the chapter `Constructing The Client` is written the following:

> The Client constructor also receives an optional "httpOptions" array, which overrides the "authorizationHeaders" and can be used to add custom Guzzle HTTP Client request options.

With the following sample code:

```
$client = new Client(
    'http://api.graphql.com',
    [],
    [ 
        'connect_timeout' => 5,
        'timeout' => 5,
        'headers' => [
            'Authorization' => 'Basic xyz'
            'User-Agent' => 'testing/1.0',
        ],
        'proxy' => [
                'http'  => 'tcp://localhost:8125', // Use this proxy with "http"
                'https' => 'tcp://localhost:9124', // Use this proxy with "https",
                'no' => ['.mit.edu', 'foo.com']    // Don't use a proxy with these
        ],
        'cert' => ['/path/server.pem', 'password']
        ...
    ]
);
```

But that does not match the actual constructor of the class which look like this:

```
    /**
     * Client constructor.
     *
     * @param string $endpointUrl
     * @param array  $authorizationHeaders
     */
    public function __construct(string $endpointUrl, array $authorizationHeaders = [])
    {
        $this->endpointUrl          = $endpointUrl;
        $this->authorizationHeaders = $authorizationHeaders;
        $this->httpClient           = new \GuzzleHttp\Client();
    }
```

There is no third constructor parameter. There is nothing passed to guzzle. Is the class constructor wrong or is the documentation outdated/incorrect?

Thanks right now.

**Comment by mghoneimy** [comment]
Hi @mschop ,
You're right there's a mismatch because the latest version hasn't been released. No tag has been created for version `1.4` yet its code is shown on master. I will release this immediately!
Thank you for pointing this out

**Comment by mghoneimy** [comment]
@mschop  Problem should be fixed now. Please try installing `v1.4` and let me know if you still have any issues. :smile:
