### ISSUE TITLE
ext-readline unused

### ISSUE THREAD

**Issue by slepic** [mghoneimy/php-graphql-client#28]
Why is ext-readline required by the package? The only occurence is in README.md in examples. But it is nowhere in the code of the library (or at least i could not find it).

```
$ find . -type f -exec grep -nH readline "{}" \;
./README.md:437:    $name = readline('Enter pokemon name: ');
./README.md:476:    $name = readline('Enter pokemon name: ');
./composer.json:34:        "ext-readline": "*",
```

**Comment by mghoneimy** [comment]
@slepic  you were right, the extension wasn't used except in REAEDME.md, pull request merged!
Thank you for your contribution :smile:
