### ISSUE TITLE
Bug: Strings are not escaped

### ISSUE THREAD

**Issue by marvinrabe** [mghoneimy/php-graphql-client#3]
When passing strings as attributes to a Query the resulting strings in the gql are not escaped.

    (new Query('users'))->setArguments(['name' => 'Lester "Lessie" McMillian'])

Currently:

    query {users(name: "Lester "Lessie" McMillian") {}}

Expected:

    query {users(name: "Lester \"Lessie\" McMillian") {}}

Test:

    public function testItEscapesStringArguments()
    {
        $result = (new Query('users'))
            ->setArguments(['name' => 'Lester "Lessie" McMillian']);

        $this->assertEquals("query {\nusers(name: \"Lester \\\"Lessie\\\" McMillian\") {\n\n}\n}", (string)$result);
    }

**Comment by mghoneimy** [comment]
@marvinrabe Thank you for finding this! Would you like to pull-request-it or can you wait until I can work on it when I can allocate time?

**Comment by mghoneimy** [comment]
Issue has been fixed in version 1.1.1 release
