### ISSUE TITLE
Why is it necessary to provide the type of variable in client?

### ISSUE THREAD

**Issue by eeromay** [mghoneimy/php-graphql-client#35]
Hi.

Why is it necessary to provide the type of variable in client via "new Variable()"?

The GraphQL server already defines which type is needed and throws an error if the type is not correct.

**Comment by mghoneimy** [comment]
Hi,

The `Variable` class acts as an abstraction layer between the package user and the GraphQL request string. You do not need to learn how to construct the variable syntax, just fill in the variable data and the package does the rest.

As for why the variable needs a type, the `Variable` class is used when defining a query, not while running one. If a query is already defined with a variable on your server, just run the query straight away using the client. You can refer to this for more details:
https://github.com/mghoneimy/php-graphql-client/pull/38/files
