### ISSUE TITLE
Base URL?

### ISSUE THREAD

**Issue by Joshgallagher** [mghoneimy/php-graphql-client#37]
Great library!

However, I can not seem to find a way to add to the `base URL` I have set?

This is my client:

```
return new Client(
    'https://' . config('shopify.store_name') . '.myshopify.com',
    ['X-Shopify-Access-Token' => config('shopify.password')]
);
```

Is there a method to extend the URL without having to change it in the client - it limits its reusability.

Thanks in advance.

**Comment by ShawnCorrigan** [comment]
Right now there is no way to do this, a client will only use the endpoint url you used when you instantiated it. Usually you will make all your requests to the same GraphQL endpoint.

**Comment by mghoneimy** [comment]
+1 to what @ShawnCorrigan said. Usually the GraphQL server runs on a single API endpoint. If there are multiple API endpoints this usually means that you have multiple GraphQL servers running with different specs, which makes instantiating different clients for them reasonable.

@Joshgallagher Can you describe the specific use case you are having trouble with please?
