### ISSUE TITLE
[FEATURE] Add option to make a GET request

### ISSUE THREAD

**Issue by oneserv-heuser** [mghoneimy/php-graphql-client#39]
At the moment the request type is hardcoded to POST (see [here](https://github.com/mghoneimy/php-graphql-client/blob/072341ed65f643708456b947afa36e400fd2bf72/src/Client.php#L96)). Many applications don't cache POST requests, but only GET requests. For non sensitive data it's totally fine to use GET requests.

I'd propose to not hardcode the request method but instead add an option to set the method when executing a query. Adding a optional parameter to [the runQuery method](https://github.com/mghoneimy/php-graphql-client/blob/072341ed65f643708456b947afa36e400fd2bf72/src/Client.php#L72) would solve this and also not require a new major release as it would be backwards compatible.

Any thoughts?

If you want me to I can solve the problem and make a PR for this feature.

**Comment by mghoneimy** [comment]
Hi @oneserv-heuser ,

I totally see your point, this a totally valid feature request.

While I agree with the need, I'm not sure if adding an extra parameter to the `runQuery` method is the best way to do this. I generally don't like it when methods have a long list of parameters and I don't want this method to move in this direction.

There are 2 options I see for implementing this:
1. The option you proposed, pass an extra parameter to indicate HTTP method type
2. Determine the HTTP method you want to use for running the requests on the server when constructing the client

Options 2 would avoid making the method signature more complex, but will limit each client to running just one type of requests in all its calls to the GraphQL server.

Let me know what you think about this.

Also, I'm open to having you handle this in a pull request. Just keep in mind that there are a few pull requests in the pipeline now around some changes to the client, so you might want to get this done quickly before they are merged, or wait for them to get merged then prepare yours.

**Comment by oneserv-heuser** [comment]
@mghoneimy I think adding another parameter is fine, especially when looking into the future with [PHP 8 Named Arguments](https://wiki.php.net/rfc/named_params). But I also like the idea of adding the parameter to the construct method of the client, as the downside of having one method per Client should be also no problem as you can just construct multiple Clients if needed.

I guess adding it as construct argument is preferable to avoid making the method signature more complex. I'll implement it right away.

**Comment by oneserv-heuser** [comment]
@mghoneimy  Done, PR is open and ready for review.
