### ISSUE TITLE
How to use a token

### ISSUE THREAD

**Issue by juanitourquiza** [mghoneimy/php-graphql-client#4]
I need to use a verification token, where that value goes?
```
$client = new Client(
    'http://192.168.57.104:3000/graphql',
    []  // Replace with array of extra headers to be sent with request for auth or other purposes
);
```

**Comment by mghoneimy** [comment]
@juanitourquiza just add a new element to the empty array where the key of the element is the header name for the verification token and the value is the verification token itself.

Example:
```
$client = new Client( 
    'http://192.168.57.104:3000/graphql',
    ['auth_header_name' => $verificationToken]
);
```
