### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by dmouse** [mghoneimy/php-graphql-client#48]
Im trying to install this package in a php 8 project but its not supported, do you know the status of compatibility with php 8?

**Comment by alexandros-bantzos** [comment]
Do we have an ETA on the next version that'd support PHP 8? Thanks and keep up the good work!

**Comment by dmouse** [comment]
probably just tag the new version of this package, if you look into the composer.json in the master branch the php 8 support are there

**Comment by mghoneimy** [comment]
Issue has been fixed with v1.9 release
https://github.com/mghoneimy/php-graphql-client/releases/tag/v1.9
