### ISSUE TITLE
Can't set string values beginning with $

### ISSUE THREAD

**Issue by aripringle** [mghoneimy/php-graphql-client#49]
We have a case where attempting to run a mutation using string values that may begin with a dollar sign ($). I believe the library always treats strings like this as variables, so they're not encapsulated in quotes in the raw GraphQL query.

Running a mutation with arguments like this: `['item_name' => '$500 test value']`

The raw graphql ends up looking like:

```
mutation {
create_item(item_name: $500 test value) { id }
}
```

Which results in this error:

> GraphQL\Exception\QueryError: Parse error on "500" (INT) at [2, 45] in /var/task/vendor/gmostafa/php-graphql-client/src/Results.php:55

I believe this is due to the check here: https://github.com/mghoneimy/php-graphql-client/blob/master/src/Util/StringLiteralFormatter.php#L22-L23

Any suggestions for a workaround, or a way to support this?

**Comment by mghoneimy** [comment]
Issue has been fixed in release 1.9.1
https://github.com/mghoneimy/php-graphql-client/releases/tag/1.9.1
