### ISSUE TITLE
Error mutation: Syntax Error: Expected :, found !

### ISSUE THREAD

**Issue by juanitourquiza** [mghoneimy/php-graphql-client#5]
I'm using the example for my code but it shows me this error. What is the problem?

```
$mutation = (new Mutation('createOBT_MOTIVO_VIAJE'))
			->setArguments(['OBT_MOTIVOS_VIAJEEntry!' => new RawObject('{NOMBRE_TIPO_MOTIVO: "prueba1", DESCRIPCION_TIPO_MOTIVO: "prueba1"}')])
			->setSelectionSet(
				[					
					'NOMBRE_TIPO_MOTIVO',
					'DESCRIPCION_TIPO_MOTIVO',
				]
			);
		//var_dump($mutation);exit;	
		$results = $client->runQuery($mutation);
```
This is the error:
Syntax Error: Expected :, found !

![image](https://user-images.githubusercontent.com/332299/60035059-94987100-9671-11e9-9361-768f9094e05d.png)

**Comment by mghoneimy** [comment]
@juanitourquiza You cannot have this 'OBT_MOTIVOS_VIAJEEntry!' as an argument name. GraphQL standards specify that an argument is made up of a Name and Value https://graphql.github.io/graphql-spec/June2018/#Argument, where name can only have alphanumeric characters https://graphql.github.io/graphql-spec/June2018/#Name.

The '!' used in type definitions in GraphQL types simply means that this argument's value is non-nullable 
https://graphql.org/learn/schema/#object-types-and-fields

That is why the GraphQL server returns an error saying "Syntax Error: Expected :, found!", because it parsed the argument name successfully and now expects a ':' to separate the name and value, but instead it found a '!'

**Comment by juanitourquiza** [comment]
Ok. Thanks for your explication. I use this code in GraphQL:
```

mutation($input: OBT_MOTIVOS_VIAJEEntry!) {
  createOBT_MOTIVO_VIAJE(input: $input) {
    NOMBRE_TIPO_MOTIVO,
    DESCRIPCION_TIPO_MOTIVO
  }
}
```
Query variables:
```

{
  "input": {
    "NOMBRE_TIPO_MOTIVO": "mutPE",
    "DESCRIPCION_TIPO_MOTIVO": "mutPE",
    "DIRECCION_IP": "localhost"
  }
}

```                
This work for me .... This is the reason for my confussion.
Now I'm going to try what you tell me

**Comment by mghoneimy** [comment]
@juanitourquiza Now I understand why you're having the problem. $input here is a GraphQL "variable" and not an argument value in itself. It's being passed as an argument to the createOBT_MOTIVO_VIAJE mutation.

Currently this package does not support using variables. You can submit this as a feature request though and start working on it as soon as I can.

You can read more about variables and arguments here:
https://graphql.org/learn/queries/#variables
https://graphql.org/learn/queries/#arguments

**Comment by juanitourquiza** [comment]
Well, thanks for your response. Perhaps the library will be improved

**Comment by mghoneimy** [comment]
I will close this issue as a question. Please open a new issue for adding support for variables in this library and will work on it as soon as I can.

**Comment by mghoneimy** [comment]
@juanitourquiza v1.2 has just been released adding support for variables in queries and mutations. Hope this solves your problems!

**Comment by marianpatak** [comment]
I tryinng to use your library but a canot simulate mutation with array  data

this is raw

        $gql = '
           mutation {
              login(input: {
                username: "myemail@email.com",
                password: "123456789qq"
              }) {
                access_token
                refresh_token
                expires_in
                token_type
                user {
                  id
                  email
                  name
                  created_at
                  updated_at
                }
              }
           }
        ';

this raw is work but othervise not, can You help mi with syntax or what I making wrong

thank You
