### ISSUE TITLE
No QueryBuilder that can be a mutation?

### ISSUE THREAD

**Issue by nealoke** [mghoneimy/php-graphql-client#50]
We have the option to use the `QueryBuilder` for queries, why not for a mutation? :)

**Comment by mghoneimy** [comment]
Hi @nealoke 
It just wasn't a priority then. It should be very simple to add one though, I can prioritize it

**Comment by mghoneimy** [comment]
This is issue is addressed by v1.10 (https://github.com/mghoneimy/php-graphql-client/releases/tag/v1.10)
