### ISSUE TITLE
nested level of arguments bug

### ISSUE THREAD

**Issue by ammaramame** [mghoneimy/php-graphql-client#57]
There some issue when i try to query data with nested level of filters for example 

`farmsByFarmerId: {aggregates: {distinctCount: {id: {equalTo: "3"}}}}`

it through array to string conversion error

could you please check it .

**Comment by mghoneimy** [comment]
In this case you will have to use the `RawObject` class

Example: https://github.com/mghoneimy/php-graphql-client#query-with-input-object-argument
