### ISSUE TITLE
Add support for AWS IAM authorization

### ISSUE THREAD

**Issue by viktor-zinchenko** [mghoneimy/php-graphql-client#59]
The idea is to add AWS IAM authorization support, so the client could be used with AWS appsync using this auth method.
Select auth type method (with header, request signing, etc.) could be used. 

AWS php sdk would be useful for signing request. Signing code example:
```
// set up key, secret, region
$credentials = new \Aws\Credentials\Credentials($key, $secret);
$signature = new \Aws\Signature\SignatureV4('appsync', $region);
$request = $signature->signRequest($request, $credentials, 'appsync');
```

@mghoneimy what do you think about it? I could prepare PR shortly if you are fine with this feature.

**Comment by mghoneimy** [comment]
Closed by #64
