### ISSUE TITLE
Client.php, line 122:  Call to undefined function GuzzleHttp\\Psr7\\stream_for()

### ISSUE THREAD

**Issue by paianoa** [mghoneimy/php-graphql-client#62]
Line 122:
` $request = $request->withBody(Psr7\stream_for(json_encode($bodyArray)));`

Should be changed to:
`
 $request = $request->withBody(Psr7\Utils::streamFor(json_encode($bodyArray)));`

**Comment by PierreGranger** [comment]
Same here, after a composer update i've got the same issue.
The update shared by @paianoa resolves the issue.

**Comment by mghoneimy** [comment]
Addressed by #61
