### ISSUE TITLE
Argument 1 passed to GuzzleHttp\Client::send() must be an instance of GuzzleHttp\Message\RequestInterface

### ISSUE THREAD

**Issue by marlexladag** [mghoneimy/php-graphql-client#63]
Type error: Argument 1 passed to GuzzleHttp\Client::send() must be an instance of GuzzleHttp\Message\RequestInterface, instance of GuzzleHttp\Psr7\Request given, called in /var/www/html/modules/solarreseller/vendor/gmostafa/php-graphql-client/src/Util/GuzzleAdapter.php on line 41

**Comment by mghoneimy** [comment]
Hello,
What version of guzzle are you using?

**Comment by mghoneimy** [comment]
I will be closing this issue as I really don't understand how it happened.
This package supports versions ^6.3|^7.0.1 of guzzle which have the ClientInteface requiriing `Psr\Http\Message\RequestInterface` in the `send()` method.
The error reported here means that the guzzle version used in your application is below the required one.
