### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by hhdivil** [mghoneimy/php-graphql-client#7]
Hi, thanks for the library.  Great so far.  I was just wondering if you have plans to add support for variables in the future?

https://graphql.org/learn/queries/#variables

**Comment by mghoneimy** [comment]
Hello @hhdivil , I'm currently working on adding variables support. Should be released by the end of the weekend/early next week.

**Comment by mghoneimy** [comment]
@hhdivil v1.2 has just been released adding support for variables in queries and mutations.
